title:              psj2867
email:              psj2867@gmail.com
description:        ""
author:             "psj2867"
baseurl:            ""
url:                ""

# Social Profiles
# twitter_username:   SBootstrap
github_username:    psj2867
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           8
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# gems:
  # - jekyll-paginate-v2

# pagination:
#     enabled: true
#     per_page: 5
#     limit: 0
#     sort_field: "date"
#     sort_reverse: true
